{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vllm-deployment.fullname" . }}
  labels:
    {{- include "vllm-deployment.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vllm-deployment.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.name }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}

