apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-deployment.fullname" . }}
  labels:
    {{- include "vllm-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "vllm-deployment.selectorLabels" . | nindent 4 }}

