apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-org-service
spec:
  template:
    spec:
      containers:
        - name: admin-api
          env:
            - name: ENVIRONMENT
              value: development
        - name: reconciler
          env:
            - name: ENVIRONMENT
              value: development


