apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-org-service.fullname" . }}
  labels:
    {{- include "user-org-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-org-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-org-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "user-org-service.serviceAccountName" . }}
      containers:
        - name: admin-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["./admin-api"]
          env:
            {{- range .Values.env }}
            {{- if .valueFrom }}
            - name: {{ .name }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.extraEnv }}
            {{- if .valueFrom }}
            - name: {{ .name }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
        - name: reconciler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["./reconciler"]
          env:
            {{- range .Values.env }}
            {{- if .valueFrom }}
            - name: {{ .name }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.extraEnv }}
            {{- if .valueFrom }}
            - name: {{ .name }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ add .Values.service.port 1 }}
              name: reconciler
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: reconciler
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: reconciler
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          {{- toYaml .volume | nindent 8 }}
        {{- end }}


