apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-org-service.serviceAccountName" . }}
  labels:
    {{- include "user-org-service.labels" . | nindent 4 }}
automountServiceAccountToken: true


