apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-portal.nginxConfigMapName" . }}
  labels:
    {{- include "web-portal.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginx.config | indent 4 }}

